### ISSUE TITLE
Store class not imported into HasSettings trait

### ISSUE THREAD

**Issue by mstralka** [artisanry/settingable#11]
The `BrianFaust\Settingable\Traits\HasSettings` trait includes this line:
~~~php
return $key ? $this->settings()->get($key) : new Store($this);
~~~

But the the `BrianFaust\Settingable\Store` class is not imported, so PHP throws a fatal error:

~~~
FatalThrowableError
Class 'BrianFaust\Settingable\Traits\Store' not found
~~~

Thanks

**Comment by faustbrian** [comment]
Feel free to send a PR.

**Comment by faustbrian** [comment]
https://github.com/artisanry/settingable/commit/08f33e1c3ac926f49d134d16ab6a2afc933408e1
